packages:
  - packages/*
  - examples/*

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cross-spawn: ^7.0.6
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  vite@>=5.0.0 <5.4.15: '>=5.4.15'
  vite@>=5.0.0 <5.4.16: '>=5.4.16'
  vite@>=5.0.0 <5.4.17: '>=5.4.17'
  vite@>=5.0.0 <5.4.18: '>=5.4.18'
  vite@>=5.0.0 <=5.4.11: '>=5.4.12'
  vite@>=5.0.0 <=5.4.18: '>=5.4.19'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
